// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AcceptFollow(ctx context.Context, respondedAt *int64, followerID int64, followeeID int64) (int64, error)
	ConsumeEmailToken(ctx context.Context, consumedAt *int64, iD int64) (int64, error)
	// CountActivities counts exactly the rows ListActivities can return for the same
	// arguments, with no LIMIT/OFFSET. Its WHERE clause is the visibility twin of
	// social.VisibilityAllows, identical to ListActivities above, and the two must
	// stay in step so a page's total matches its rows.
	CountActivities(ctx context.Context, ownerID int64, feedMe int64, viewerID int64, followingOnly int64, sportFilter string, search string) (int64, error)
	CountActivityMedia(ctx context.Context, activityID int64) (int64, error)
	CountComments(ctx context.Context, activityID int64) (int64, error)
	CountFollowers(ctx context.Context, followeeID int64) (int64, error)
	CountFollowing(ctx context.Context, followerID int64) (int64, error)
	CountIdentitiesForUser(ctx context.Context, userID int64) (int64, error)
	CountLikes(ctx context.Context, activityID int64) (int64, error)
	CountPrivacyZones(ctx context.Context, userID int64) (int64, error)
	// How many of the five most recent runs for a connection failed; the worker
	// uses it as the exponent of its backoff.
	CountRecentFailedRuns(ctx context.Context, userID int64, connectionKind string) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID int64) (int64, error)
	CountUserActivities(ctx context.Context, userID int64) (int64, error)
	CreateAPIKey(ctx context.Context, userID int64, name string, keyHash []byte, prefix string, createdAt int64) (ApiKey, error)
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	CreateComment(ctx context.Context, activityID int64, userID int64, body string, createdAt int64) (Comment, error)
	CreateEmailToken(ctx context.Context, userID int64, kind string, tokenHash []byte, expiresAt int64, createdAt int64) (int64, error)
	// A row that has already been sent, or is still pending, keeps its place, so
	// the handler can report a conflict. A row that ended in error is reset, which
	// is the only way a failed export can ever be retried.
	CreateExport(ctx context.Context, activityID int64, userID int64, target string, externalID string, createdAt int64, updatedAt int64) (int64, error)
	CreateIdentity(ctx context.Context, userID int64, provider string, providerUserID string, email *string, createdAt int64) (AuthIdentity, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreateMention(ctx context.Context, commentID int64, mentionedUserID int64) error
	CreateNotification(ctx context.Context, userID int64, actorID int64, kind string, activityID *int64, commentID *int64, createdAt int64) (Notification, error)
	CreatePrivacyZone(ctx context.Context, userID int64, label string, lat float64, lon float64, radiusM int64, createdAt int64) (PrivacyZone, error)
	CreateSession(ctx context.Context, userID int64, tokenHash []byte, createdAt int64, expiresAt int64, userAgent string, ip string) (Session, error)
	CreateSyncRun(ctx context.Context, userID int64, connectionKind string, startedAt int64) (SyncRun, error)
	CreateTombstone(ctx context.Context, userID int64, dedupeHash string, deletedAt int64) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteActivity(ctx context.Context, id int64) (int64, error)
	DeleteConnection(ctx context.Context, userID int64, kind string) (int64, error)
	DeleteExpiredSessions(ctx context.Context, expiresAt int64) (int64, error)
	DeleteFollow(ctx context.Context, followerID int64, followeeID int64) (int64, error)
	DeleteIdentity(ctx context.Context, userID int64, provider string) (int64, error)
	DeleteImportRulesForConnection(ctx context.Context, userID int64, connectionKind string) (int64, error)
	DeleteOtherSessionsForUser(ctx context.Context, userID int64, tokenHash []byte) (int64, error)
	// Pending rows are removed only for the target the disconnected provider owns.
	// Sent and errored rows stay as history. intervals.icu owns no export target.
	DeletePendingExportsForTarget(ctx context.Context, userID int64, target string) (int64, error)
	DeletePrivacyZone(ctx context.Context, iD int64, userID int64) (int64, error)
	DeleteSession(ctx context.Context, tokenHash []byte) (int64, error)
	DeleteSessionsForUser(ctx context.Context, userID int64) (int64, error)
	EmailTaken(ctx context.Context, email string) (int64, error)
	FinishSyncRun(ctx context.Context, finishedAt *int64, imported int64, skipped int64, error *string, iD int64) (int64, error)
	GetAPIKeyByHash(ctx context.Context, keyHash []byte) (ApiKey, error)
	GetActiveAvatar(ctx context.Context, userID int64) (Medium, error)
	GetActivity(ctx context.Context, id int64) (Activity, error)
	GetActivityByDedupe(ctx context.Context, userID int64, dedupeHash string) (Activity, error)
	GetActivityBySourceRef(ctx context.Context, userID int64, source string, sourceRef *string) (Activity, error)
	// Same visibility predicate as ListActivities above.
	GetActivityTotalsBySport(ctx context.Context, ownerID int64, fromTs int64, toTs int64, viewerID int64) ([]GetActivityTotalsBySportRow, error)
	GetComment(ctx context.Context, id int64) (Comment, error)
	GetConnection(ctx context.Context, userID int64, kind string) (Connection, error)
	GetConnectionByExternalID(ctx context.Context, kind string, externalAthleteID *string) (Connection, error)
	GetEmailToken(ctx context.Context, tokenHash []byte, kind string) (EmailToken, error)
	GetExport(ctx context.Context, activityID int64, target string) (ActivityExport, error)
	GetFollow(ctx context.Context, followerID int64, followeeID int64) (Follow, error)
	GetIdentity(ctx context.Context, provider string, providerUserID string) (AuthIdentity, error)
	GetLike(ctx context.Context, activityID int64, userID int64) (Like, error)
	GetMedia(ctx context.Context, id int64) (Medium, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error)
	GetTombstone(ctx context.Context, userID int64, dedupeHash string) (ActivityTombstone, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	InsertLike(ctx context.Context, activityID int64, userID int64, createdAt int64) error
	InvalidateEmailTokens(ctx context.Context, consumedAt *int64, userID int64, kind string) (int64, error)
	ListAPIKeys(ctx context.Context, userID int64) ([]ApiKey, error)
	// The CASE expression below is the SQL twin of social.VisibilityAllows: it
	// resolves an activity's `default` visibility to its owner's
	// activities_visibility, then decides whether the viewer is allowed. The two
	// must keep agreeing, which TestVisibilityAgreesWithSQL asserts. CountActivities
	// repeats this predicate verbatim and must stay in step with it too, or a
	// page's total would disagree with the rows the list can return.
	//
	// One query serves every activity list:
	//   home feed        owner_id = 0, feed_me = 0, following_only = 1
	//   feed=me          owner_id = 0, feed_me = 1, following_only = 0
	//   a profile page   owner_id = <profile>, feed_me = 0, following_only = 0
	//
	// Rows are ordered by when the activity happened (started_at DESC, id DESC for
	// the tiebreak), not by insertion order, so a late import (intervals sync) does
	// not jump to the top of the feed. Activity lists are page-numbered: the
	// handler turns ?page= into LIMIT/OFFSET and pairs it with the CountActivities
	// total, so page N always holds the same rows because the sort order is total.
	//
	// search = '' disables the text filter; otherwise it matches title or
	// description with a case-insensitive LIKE. It is applied after the visibility
	// predicate and can never widen what the viewer may see.
	//
	ListActivities(ctx context.Context, arg ListActivitiesParams) ([]ListActivitiesRow, error)
	ListActivityMedia(ctx context.Context, activityID int64) ([]Medium, error)
	ListActivityPoints(ctx context.Context, activityID int64) ([]ActivityPoint, error)
	ListComments(ctx context.Context, activityID int64, beforeID int64, limitCount int64) ([]ListCommentsRow, error)
	ListConnectionsForUser(ctx context.Context, userID int64) ([]Connection, error)
	ListIdentitiesForUser(ctx context.Context, userID int64) ([]AuthIdentity, error)
	ListImportRules(ctx context.Context, userID int64) ([]ImportRule, error)
	ListMentionsForComments(ctx context.Context, commentIds []int64) ([]ListMentionsForCommentsRow, error)
	ListNotifications(ctx context.Context, userID int64, beforeID int64, limitCount int64) ([]ListNotificationsRow, error)
	ListPendingExports(ctx context.Context, limit int64) ([]ActivityExport, error)
	ListPointsForActivities(ctx context.Context, activityIds []int64) ([]ActivityPoint, error)
	ListPrivacyZones(ctx context.Context, userID int64) ([]PrivacyZone, error)
	ListRecentSyncRuns(ctx context.Context, userID int64, limit int64) ([]SyncRun, error)
	// Only the intervals.icu kinds are importable: the sync worker speaks the
	// intervals API, so a Strava row (whose stored credential is a Strava token)
	// must never be handed to it.
	ListSyncableConnections(ctx context.Context, nextAttemptAt *int64) ([]Connection, error)
	MarkAllNotificationsRead(ctx context.Context, readAt *int64, userID int64) (int64, error)
	MarkEmailVerified(ctx context.Context, updatedAt int64, iD int64) (int64, error)
	MarkNotificationRead(ctx context.Context, readAt *int64, iD int64, userID int64) (int64, error)
	NextMediaPosition(ctx context.Context, activityID int64) (int64, error)
	RevokeAPIKey(ctx context.Context, revokedAt *int64, iD int64, userID int64) (int64, error)
	SearchUsers(ctx context.Context, query string, limitCount int64) ([]User, error)
	SoftDeleteComment(ctx context.Context, deletedAt *int64, iD int64) (int64, error)
	SoftDeleteMedia(ctx context.Context, deletedAt *int64, iD int64) (int64, error)
	TouchAPIKey(ctx context.Context, lastUsedAt *int64, iD int64) error
	UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error)
	UpdateConnectionAthleteID(ctx context.Context, externalAthleteID *string, updatedAt int64, iD int64) (int64, error)
	UpdateConnectionError(ctx context.Context, lastError *string, nextAttemptAt *int64, updatedAt int64, iD int64) (int64, error)
	UpdateConnectionSettings(ctx context.Context, autoExport bool, exportMessage string, updatedAt int64, userID int64, kind string) (int64, error)
	UpdateConnectionSyncState(ctx context.Context, syncedFrom *int64, lastSuccessAt *int64, updatedAt int64, iD int64) (int64, error)
	UpdateConnectionTokens(ctx context.Context, accessTokenCipher []byte, refreshTokenCipher []byte, tokenExpiresAt *int64, updatedAt int64, iD int64) (int64, error)
	UpdateExportStatus(ctx context.Context, status string, remoteID *string, attempts int64, lastError *string, updatedAt int64, iD int64) (int64, error)
	UpdateMediaSize(ctx context.Context, width int64, height int64, bytes int64, iD int64) (int64, error)
	UpdateSessionExpiry(ctx context.Context, createdAt int64, expiresAt int64, iD int64) (int64, error)
	UpdateUserEmail(ctx context.Context, email string, emailVerified bool, updatedAt int64, iD int64) (int64, error)
	UpdateUserPassword(ctx context.Context, passwordHash *string, updatedAt int64, iD int64) (int64, error)
	UpdateUserPrivacy(ctx context.Context, arg UpdateUserPrivacyParams) (User, error)
	UpdateUserProfile(ctx context.Context, displayName string, bio string, updatedAt int64, iD int64) (User, error)
	UpsertConnection(ctx context.Context, arg UpsertConnectionParams) (Connection, error)
	UpsertFollow(ctx context.Context, followerID int64, followeeID int64, status string, createdAt int64) error
	UpsertImportRule(ctx context.Context, userID int64, connectionKind string, sport string, enabled bool, updatedAt int64) error
	UsernameTaken(ctx context.Context, username string) (int64, error)
}

var _ Querier = (*Queries)(nil)
