// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package db

import (
	"context"
)

const countRecentFailedRuns = `-- name: CountRecentFailedRuns :one
SELECT CAST(COUNT(*) AS INTEGER) FROM (
    SELECT error FROM sync_runs
    WHERE user_id = ? AND connection_kind = ?
    ORDER BY id DESC LIMIT 5
) WHERE error IS NOT NULL
`

// How many of the five most recent runs for a connection failed; the worker
// uses it as the exponent of its backoff.
func (q *Queries) CountRecentFailedRuns(ctx context.Context, userID int64, connectionKind string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentFailedRuns, userID, connectionKind)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createExport = `-- name: CreateExport :execrows
INSERT INTO activity_exports (activity_id, user_id, target, status, external_id, created_at, updated_at)
VALUES (?, ?, ?, 'pending', ?, ?, ?)
ON CONFLICT (activity_id, target) DO UPDATE SET
    status = 'pending',
    attempts = 0,
    last_error = NULL,
    updated_at = excluded.updated_at
WHERE activity_exports.status = 'error'
`

// A row that has already been sent, or is still pending, keeps its place, so
// the handler can report a conflict. A row that ended in error is reset, which
// is the only way a failed export can ever be retried.
func (q *Queries) CreateExport(ctx context.Context, activityID int64, userID int64, target string, externalID string, createdAt int64, updatedAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, createExport,
		activityID,
		userID,
		target,
		externalID,
		createdAt,
		updatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createSyncRun = `-- name: CreateSyncRun :one
INSERT INTO sync_runs (user_id, connection_kind, started_at)
VALUES (?, ?, ?)
RETURNING id, user_id, connection_kind, started_at, finished_at, imported, skipped, error
`

func (q *Queries) CreateSyncRun(ctx context.Context, userID int64, connectionKind string, startedAt int64) (SyncRun, error) {
	row := q.db.QueryRowContext(ctx, createSyncRun, userID, connectionKind, startedAt)
	var i SyncRun
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ConnectionKind,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Imported,
		&i.Skipped,
		&i.Error,
	)
	return i, err
}

const deleteConnection = `-- name: DeleteConnection :execrows
DELETE FROM connections WHERE user_id = ? AND kind = ?
`

func (q *Queries) DeleteConnection(ctx context.Context, userID int64, kind string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteConnection, userID, kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteImportRulesForConnection = `-- name: DeleteImportRulesForConnection :execrows
DELETE FROM import_rules WHERE user_id = ? AND connection_kind = ?
`

func (q *Queries) DeleteImportRulesForConnection(ctx context.Context, userID int64, connectionKind string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteImportRulesForConnection, userID, connectionKind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePendingExportsForTarget = `-- name: DeletePendingExportsForTarget :execrows
DELETE FROM activity_exports
WHERE user_id = ? AND target = ? AND status = 'pending'
`

// Pending rows are removed only for the target the disconnected provider owns.
// Sent and errored rows stay as history. intervals.icu owns no export target.
func (q *Queries) DeletePendingExportsForTarget(ctx context.Context, userID int64, target string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePendingExportsForTarget, userID, target)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishSyncRun = `-- name: FinishSyncRun :execrows
UPDATE sync_runs
SET finished_at = ?, imported = ?, skipped = ?, error = ?
WHERE id = ?
`

func (q *Queries) FinishSyncRun(ctx context.Context, finishedAt *int64, imported int64, skipped int64, error *string, iD int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishSyncRun,
		finishedAt,
		imported,
		skipped,
		error,
		iD,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getConnection = `-- name: GetConnection :one
SELECT id, user_id, kind, external_athlete_id, access_token_cipher, refresh_token_cipher, token_expires_at, auto_export, export_message, synced_from, last_success_at, last_error, next_attempt_at, created_at, updated_at FROM connections WHERE user_id = ? AND kind = ?
`

func (q *Queries) GetConnection(ctx context.Context, userID int64, kind string) (Connection, error) {
	row := q.db.QueryRowContext(ctx, getConnection, userID, kind)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.ExternalAthleteID,
		&i.AccessTokenCipher,
		&i.RefreshTokenCipher,
		&i.TokenExpiresAt,
		&i.AutoExport,
		&i.ExportMessage,
		&i.SyncedFrom,
		&i.LastSuccessAt,
		&i.LastError,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectionByExternalID = `-- name: GetConnectionByExternalID :one
SELECT id, user_id, kind, external_athlete_id, access_token_cipher, refresh_token_cipher, token_expires_at, auto_export, export_message, synced_from, last_success_at, last_error, next_attempt_at, created_at, updated_at FROM connections WHERE kind = ? AND external_athlete_id = ?
`

func (q *Queries) GetConnectionByExternalID(ctx context.Context, kind string, externalAthleteID *string) (Connection, error) {
	row := q.db.QueryRowContext(ctx, getConnectionByExternalID, kind, externalAthleteID)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.ExternalAthleteID,
		&i.AccessTokenCipher,
		&i.RefreshTokenCipher,
		&i.TokenExpiresAt,
		&i.AutoExport,
		&i.ExportMessage,
		&i.SyncedFrom,
		&i.LastSuccessAt,
		&i.LastError,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExport = `-- name: GetExport :one
SELECT id, activity_id, user_id, target, status, external_id, remote_id, attempts, last_error, created_at, updated_at FROM activity_exports WHERE activity_id = ? AND target = ?
`

func (q *Queries) GetExport(ctx context.Context, activityID int64, target string) (ActivityExport, error) {
	row := q.db.QueryRowContext(ctx, getExport, activityID, target)
	var i ActivityExport
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.UserID,
		&i.Target,
		&i.Status,
		&i.ExternalID,
		&i.RemoteID,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectionsForUser = `-- name: ListConnectionsForUser :many
SELECT id, user_id, kind, external_athlete_id, access_token_cipher, refresh_token_cipher, token_expires_at, auto_export, export_message, synced_from, last_success_at, last_error, next_attempt_at, created_at, updated_at FROM connections WHERE user_id = ? ORDER BY kind
`

func (q *Queries) ListConnectionsForUser(ctx context.Context, userID int64) ([]Connection, error) {
	rows, err := q.db.QueryContext(ctx, listConnectionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.ExternalAthleteID,
			&i.AccessTokenCipher,
			&i.RefreshTokenCipher,
			&i.TokenExpiresAt,
			&i.AutoExport,
			&i.ExportMessage,
			&i.SyncedFrom,
			&i.LastSuccessAt,
			&i.LastError,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportRules = `-- name: ListImportRules :many
SELECT id, user_id, connection_kind, sport, enabled, updated_at FROM import_rules WHERE user_id = ? ORDER BY connection_kind, sport
`

func (q *Queries) ListImportRules(ctx context.Context, userID int64) ([]ImportRule, error) {
	rows, err := q.db.QueryContext(ctx, listImportRules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportRule{}
	for rows.Next() {
		var i ImportRule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConnectionKind,
			&i.Sport,
			&i.Enabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingExports = `-- name: ListPendingExports :many
SELECT id, activity_id, user_id, target, status, external_id, remote_id, attempts, last_error, created_at, updated_at FROM activity_exports
WHERE status = 'pending' AND attempts < 5
ORDER BY id
LIMIT ?
`

func (q *Queries) ListPendingExports(ctx context.Context, limit int64) ([]ActivityExport, error) {
	rows, err := q.db.QueryContext(ctx, listPendingExports, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityExport{}
	for rows.Next() {
		var i ActivityExport
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.UserID,
			&i.Target,
			&i.Status,
			&i.ExternalID,
			&i.RemoteID,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSyncRuns = `-- name: ListRecentSyncRuns :many
SELECT id, user_id, connection_kind, started_at, finished_at, imported, skipped, error FROM sync_runs WHERE user_id = ? ORDER BY id DESC LIMIT ?
`

func (q *Queries) ListRecentSyncRuns(ctx context.Context, userID int64, limit int64) ([]SyncRun, error) {
	rows, err := q.db.QueryContext(ctx, listRecentSyncRuns, userID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncRun{}
	for rows.Next() {
		var i SyncRun
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConnectionKind,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Imported,
			&i.Skipped,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncableConnections = `-- name: ListSyncableConnections :many
SELECT id, user_id, kind, external_athlete_id, access_token_cipher, refresh_token_cipher, token_expires_at, auto_export, export_message, synced_from, last_success_at, last_error, next_attempt_at, created_at, updated_at FROM connections
WHERE kind IN ('intervals_oauth', 'intervals_apikey')
  AND (next_attempt_at IS NULL OR next_attempt_at <= ?)
ORDER BY id
`

// Only the intervals.icu kinds are importable: the sync worker speaks the
// intervals API, so a Strava row (whose stored credential is a Strava token)
// must never be handed to it.
func (q *Queries) ListSyncableConnections(ctx context.Context, nextAttemptAt *int64) ([]Connection, error) {
	rows, err := q.db.QueryContext(ctx, listSyncableConnections, nextAttemptAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Connection{}
	for rows.Next() {
		var i Connection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.ExternalAthleteID,
			&i.AccessTokenCipher,
			&i.RefreshTokenCipher,
			&i.TokenExpiresAt,
			&i.AutoExport,
			&i.ExportMessage,
			&i.SyncedFrom,
			&i.LastSuccessAt,
			&i.LastError,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnectionAthleteID = `-- name: UpdateConnectionAthleteID :execrows
UPDATE connections
SET external_athlete_id = ?, updated_at = ?
WHERE id = ?
`

func (q *Queries) UpdateConnectionAthleteID(ctx context.Context, externalAthleteID *string, updatedAt int64, iD int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateConnectionAthleteID, externalAthleteID, updatedAt, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateConnectionError = `-- name: UpdateConnectionError :execrows
UPDATE connections
SET last_error = ?, next_attempt_at = ?, updated_at = ?
WHERE id = ?
`

func (q *Queries) UpdateConnectionError(ctx context.Context, lastError *string, nextAttemptAt *int64, updatedAt int64, iD int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateConnectionError,
		lastError,
		nextAttemptAt,
		updatedAt,
		iD,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateConnectionSettings = `-- name: UpdateConnectionSettings :execrows
UPDATE connections
SET auto_export = ?, export_message = ?, updated_at = ?
WHERE user_id = ? AND kind = ?
`

func (q *Queries) UpdateConnectionSettings(ctx context.Context, autoExport bool, exportMessage string, updatedAt int64, userID int64, kind string) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateConnectionSettings,
		autoExport,
		exportMessage,
		updatedAt,
		userID,
		kind,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateConnectionSyncState = `-- name: UpdateConnectionSyncState :execrows
UPDATE connections
SET synced_from = ?, last_success_at = ?, last_error = NULL, next_attempt_at = NULL, updated_at = ?
WHERE id = ?
`

func (q *Queries) UpdateConnectionSyncState(ctx context.Context, syncedFrom *int64, lastSuccessAt *int64, updatedAt int64, iD int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateConnectionSyncState,
		syncedFrom,
		lastSuccessAt,
		updatedAt,
		iD,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateConnectionTokens = `-- name: UpdateConnectionTokens :execrows
UPDATE connections
SET access_token_cipher = ?, refresh_token_cipher = ?, token_expires_at = ?, updated_at = ?
WHERE id = ?
`

func (q *Queries) UpdateConnectionTokens(ctx context.Context, accessTokenCipher []byte, refreshTokenCipher []byte, tokenExpiresAt *int64, updatedAt int64, iD int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateConnectionTokens,
		accessTokenCipher,
		refreshTokenCipher,
		tokenExpiresAt,
		updatedAt,
		iD,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateExportStatus = `-- name: UpdateExportStatus :execrows
UPDATE activity_exports
SET status = ?, remote_id = ?, attempts = ?, last_error = ?, updated_at = ?
WHERE id = ?
`

func (q *Queries) UpdateExportStatus(ctx context.Context, status string, remoteID *string, attempts int64, lastError *string, updatedAt int64, iD int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateExportStatus,
		status,
		remoteID,
		attempts,
		lastError,
		updatedAt,
		iD,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertConnection = `-- name: UpsertConnection :one
INSERT INTO connections (
    user_id, kind, external_athlete_id, access_token_cipher, refresh_token_cipher,
    token_expires_at, auto_export, export_message, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (user_id, kind) DO UPDATE SET
    external_athlete_id = excluded.external_athlete_id,
    access_token_cipher = excluded.access_token_cipher,
    refresh_token_cipher = excluded.refresh_token_cipher,
    token_expires_at = excluded.token_expires_at,
    last_error = NULL,
    next_attempt_at = NULL,
    updated_at = excluded.updated_at
RETURNING id, user_id, kind, external_athlete_id, access_token_cipher, refresh_token_cipher, token_expires_at, auto_export, export_message, synced_from, last_success_at, last_error, next_attempt_at, created_at, updated_at
`

type UpsertConnectionParams struct {
	UserID             int64
	Kind               string
	ExternalAthleteID  *string
	AccessTokenCipher  []byte
	RefreshTokenCipher []byte
	TokenExpiresAt     *int64
	AutoExport         bool
	ExportMessage      string
	CreatedAt          int64
	UpdatedAt          int64
}

func (q *Queries) UpsertConnection(ctx context.Context, arg UpsertConnectionParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, upsertConnection,
		arg.UserID,
		arg.Kind,
		arg.ExternalAthleteID,
		arg.AccessTokenCipher,
		arg.RefreshTokenCipher,
		arg.TokenExpiresAt,
		arg.AutoExport,
		arg.ExportMessage,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Connection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.ExternalAthleteID,
		&i.AccessTokenCipher,
		&i.RefreshTokenCipher,
		&i.TokenExpiresAt,
		&i.AutoExport,
		&i.ExportMessage,
		&i.SyncedFrom,
		&i.LastSuccessAt,
		&i.LastError,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertImportRule = `-- name: UpsertImportRule :exec
INSERT INTO import_rules (user_id, connection_kind, sport, enabled, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (user_id, connection_kind, sport) DO UPDATE
    SET enabled = excluded.enabled, updated_at = excluded.updated_at
`

func (q *Queries) UpsertImportRule(ctx context.Context, userID int64, connectionKind string, sport string, enabled bool, updatedAt int64) error {
	_, err := q.db.ExecContext(ctx, upsertImportRule,
		userID,
		connectionKind,
		sport,
		enabled,
		updatedAt,
	)
	return err
}
